//
//  EncapErrors.h
//  Encap
//
//  Copyright (c) 2013 Encap. All rights reserved.
//

#import <Foundation/Foundation.h>


typedef NS_ENUM(NSInteger, EncapError) {
    
    // --- Errors generated by the API
    
    /** Another operation in progress. Wait for it to finish before issuing new requests. */
    EncapClientErrorOperationInProgress                      = 100,
    
    /** The server could not be reached. The network may be down, there may be firewall issues, or the server may be suffering high loads. */
    EncapClientErrorConnectionFailure                        = 101,
    
    /** The server response could not be understood by the Encap API. This may occur for example because of an internal server error, or a malconfigured reverse proxy. */
    EncapClientErrorInvalidResponse                          = 102,
    
    /** The given input does not comply with the policy proposed by Encap server. */
    EncapClientErrorInvalidInputFormat                       = 105,
    
    /** The client has not yet been activated or was deactivated (not preceded by a successful activate call). */
    EncapClientErrorNotActivated                             = 106,
    
    /** An unexpected problem occurred. */
    EncapClientErrorUnexpected                               = 109,
    
    /** Attempted operaion is not allowed in this state (ex a sign operation has been requested but not proceded by a successful authenticate call). */
    EncapClientErrorWrongState                               = 110,
    
    /** Configuration error, attempted operation is not possible to perform with current configuration (ex: signing is disabled) */
    EncapClientErrorConfiguration                            = 111,
    
    /** The request to Encap server Timed out. */
    EncapClientErrorConnectionTimeout                        = 120,
    
    /** No Internet connection */
    EncapClientErrorNoInternetConnection                     = 121,

    /** Secure connection check performed by the client failed. */
    EncapClientErrorSecureConnectionCheckFailed              = 122,
    
    /** Invalid Auth parameters provided */
    EncapClientErrorInvalidAuthParameters                    = 127,

    /** Authentication method not supported or active (Ex TouchID or has been disabled) */
    EncapClientErrorAuthMethodUnavailable                    = 128,

    /** Auth method not activated or not supported for this operation */
    EncapClientErrorAuthMethodNotAllowed                     = 129,
    
    /** Authentication failed */
    EncapClientErrorAuthenticationFailed                     = 130,
    
    /** Authentication aborted */
    EncapClientErrorAuthenticationAborted                    = 131,
    
    /** Authentication data invalidated, ex fingerprints has been added or removed when using strongTouchID */
    EncapClientErrorAuthDataInvalidated                      = 132,
    
    /** API has been downgraded by developer, and current state is not supported. Remove and reinstall the app to resolve the issue. */
    EncapClientErrorDowngradeDetected                        = 133,
    
    /** A local deactivation has been performed since registration data is missing, the most likely cause is that user has backed up and restored his device */
    EncapClientErrorRegistrationDataInvalidated              = 134,
    
    /** An error occurred while reading/writing client data. This could for example happen if the device is short on storage capacity. */
    EncapClientErrorStorage                                  = 172,
    
    /** Storage is unavailable, failed to read or write data, this could for example occur if device is locked. */
    EncapClientErrorStorageUnavailable                       = 174,
    
    
    // --- Errors returned by the Encap Server
    
    /** The given activation code was incorrect. */
    EncapServerErrorIncorrectActivationCode                 = 200,
    
    /** An unexpected problem occurred. */
    EncapServerErrorUnexpected                              = 201,
    
    /** The registration is not yet known to the server (anymore). The registration ID may be incorrect or the registration may have been deleted from the server. */
    EncapServerErrorNotRegistered                           = 202,
    
    /** The session has already been authenticated (call that doesn't require authentication after successful authentication call). */
    EncapServerErrorAlreadyAuthenticated                    = 207,
    
    /** No active session found for the request. */
    EncapServerErrorNoSession                               = 208,
    
    /** The active session has expired and cannot be used anymore.  A new session must be created by the user (service provider). */
    EncapServerErrorExpiredSession                          = 209,
    
    /** The server requires push validation but the client did not provide a valid pushSessionId for the active session. */
    EncapServerErrorIncorrectPush                           = 210,
    
    /** The server is configured to disallow client-initiated sessions. */
    EncapServerErrorClientOnlyDisallowed                    = 211,
    
    /** Incorrect response to authentication challenge, ex wrong PIN, authentication failed */
    EncapServerErrorAuthenticationFailed                    = 214,
    
    /** The signature generated by the client could not be validated by the registration's public key. */
    EncapServerErrorIncorrectSignature                      = 216,
    
    /** The signature generated by the client could not be validated (missing, corrupt or of an incorrect format). */
    EncapServerErrorInvalidSignature                        = 217,
    
    /** The app ID sent by the client did not match the app ID expected by the server. */
    EncapServerErrorApplicationIdMismatch                   = 219,
    
    /** The server could not be reached or having technical difficulties */
    EncapServerErrorServiceUnavailable                      = 221,
    
    /** The registration was locked down by by admin / customer support */
    EncapServerErrorLockedByAdmin                           = 224,
    
    /** The registration was locked down by the server because authentication failed */
    EncapServerErrorLocked                                  = 226,

    /** Could not find authentication method with same or higher factors as request */
    EncapServerErrorNoMatchingAuthMethod                    = 230,
    
    /** Client tried to activate with authentication method not allowed by server's configuration. */
    EncapServerErrorIllegalAuthMethod                       = 231,
    
    /** Trying to use 1FA when 2FA is required */
    EncapServerErrorIllegalAuthFactor                       = 232,
    
    /** An authentication is required to be able to use this operation (to upgrade to new protocol). */
    EncapServerErrorAuthenticationRequired                  = 233,
    
    /** The registration must be activated with PIN to add new or update auth methods. */
    EncapServerErrorMustBeActivatedWithPin                  = 234,
    
    /** A session exists with another purpose set than in the request from the client */
    EncapServerErrorNoSessionForPurpose                     = 236,
    
    /** Application id does not exist */
    EncapServerErrorApplicationIdNotFound                   = 237,
    
    /** API version is too old for the server. */
    EncapServerErrorApiVersionTooOldForServer               = 238,
    
    /** API version precedes the server. */
    EncapServerErrorApiVersionTooNewForServer               = 239,
    
    /** The app config has specified the version as out-dated. */
    EncapServerErrorApiVersionTooOldForAppConfig            = 240,
    
    /** The app config has explicitly blacklisted this version .*/
    EncapServerErrorApiVersionBlacklisted                   = 241,
    
    /** Something has gone wrong with the communication between the server and the service provider.*/
    EncapServerErrorServerToServiceProvider                 = 242,
    
    /** Internal request parameter is not parsable. */
    EncapServerErrorNotParsable                             = 243,
    
    /** Internal request is missing a required input parameter. */
    EncapServerErrorMissingParameter                        = 244,
    
    /** Internal request parameter is malformed. */
    EncapServerErrorMalformedParameter                      = 245,
    
    /** Start activation failed but the client tried to finish activation anyway */
    EncapServerErrorActivationFailed                        = 246,
    
    /** Timeout waiting for intermediate push. */
    EncapServerErrorIntermediatePushTimeout                 = 247,
    
    /** Push is not enabled on client. */
    EncapServerErrorIntermediatePushNotEnabled              = 248,
    
    /** The request has an older timestamp than the previous request.  Either the request was delayed on the way, or the clock on the phone has been set back in time. */
    EncapServerErrorClientRequestTimeOutOfSync              = 249,
        
    /** Reactivation must be performed on the same device as it was activated on. */
    EncapServerErrorReactivationOnUnknownDevice             = 250
};

EncapError EncapErrorForKey(NSString *errorKey);
NSString *EncapLocalizationKeyForError(EncapError encapError);
